---
- name: install R
  package: name=r-base state=present
  become: yes

- name: create R user library directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/R/library"
    state: directory
  when: ansible_os_family != 'Darwin'

- name: create .Rprofile file
  lineinfile:
    path: "{{ ansible_env.HOME }}/.Rprofile"
    line: ".libPaths(\"{{ ansible_env.HOME }}/.local/share/R/library\")"
    create: yes

- name: obtain R library path
  command: Rscript -e '.libPaths()[1]'
  register: rlp_out
- name: set rlibpath fact
  set_fact: rlibpath="{{ rlp_out.stdout | regex_replace('^\\[\\d+\\]\\s*\"(.*)\"$', '\\1') }}"

- name: install R packages
  command: Rscript -e "install.packages('{{ item }}', repos='http://cran.rstudio.com')"
  args:
    creates: "{{ rlibpath }}/{{ item }}"
  loop: "{{ R_packages }}"

- name: grab RStudio release tags via curl
  uri:
    url: https://api.github.com/repos/rstudio/rstudio/tags
    return_content: yes
  register: rstudio_tags_json

- name: grab latest RStudio release
  set_fact:
    rstudio_release: "{{ (rstudio_tags_json.content | from_json)[0].name[1:] }}"

- name: install RStudio package
  apt:
    deb: "https://download1.rstudio.org/desktop/bionic/amd64/rstudio-{{ rstudio_release }}-amd64.deb"
  become: yes
