---
- name: install R
  package: name=r-base state=present
  become: yes

- name: create R user library directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/R/library"
    state: directory
  when: ansible_os_family != 'Darwin'

- name: create .Rprofile file
  lineinfile:
    path: "{{ ansible_env.HOME }}/.Rprofile"
    line: ".libPaths(\"{{ ansible_env.HOME }}/.local/share/R/library\")"
    create: yes

- name: obtain R library path
  command: Rscript -e '.libPaths()[1]'
  register: rlp_out
- name: set rlibpath fact
  set_fact: rlibpath="{{ rlp_out.stdout | regex_replace('^\\[\\d+\\]\\s*\"(.*)\"$', '\\1') }}"

- name: install R packages
  command: Rscript -e "install.packages('{{ item }}', repos='http://cran.rstudio.com')"
  args:
    creates: "{{ rlibpath }}/{{ item }}"
  loop: "{{ R_packages }}"
