---
- name: install rustup / rust
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  args:
    creates: "{{ home }}/.cargo/bin/rustup"

- name: install rust dev components
  command: "{{ home }}/.cargo/bin/rustup component add {{ item }}"
  loop: "{{ rust_components }}"

- name: install cargo global packages
  command: "{{ home }}/.cargo/bin/cargo install {{ item.package }}"
  args:
    creates: "{{ home }}/.cargo/bin/{{ item.bin }}"
  loop: "{{ cargo_packages }}"
