---
- name: install fish
  package:
    name: fish
    state: present
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"

- name: find fishs path
  command: which fish
  register: which_fish

- name: add fish to /etc/shells
  lineinfile: dest=/etc/shells line="{{ which_fish.stdout }}" state=present
  become: yes

- name: set user shell to fish
  command: chsh -s "{{ which_fish.stdout }}" "{{ ansible_user_id }}"
  become: yes
  when: ansible_user_shell != which_fish.stdout

- name: create fish functions directory
  file: path="{{ home }}/.config/fish/functions" state=directory

- name: install fisher
  get_url: url=http://git.io/fisher dest="{{ home }}/.config/fish/functions/fisher.fish"

- name: link fishfile
  file: path="{{ home }}/.config/fish/fishfile" src="{{ src_dir }}/dotfiles/fish/fishfile" state=link force=yes

- name: install fisher packages
  expect:
    command: "{{ which_fish.stdout }} -l -i"
    responses:
      ">":
        - fisher
        - exit

- name: create fish conf.d directory
  file: path="{{ home }}/.config/fish/conf.d" state=directory

- name: link conf.d files
  file: path="{{ home }}/.config/fish/conf.d/{{ item }}" src="{{ src_dir }}/dotfiles/fish/conf.d/{{ item }}" state=link force=yes
  with_items:
    - editor.fish
    - git.fish

- name: install pkgfile (cmd not found hook)
  package:
    name: pkgfile
    state: present
  become: yes
  when: ansible_os_family == 'Archlinux'
  register: install_pkgfile

- name: update pkgfile database
  command: pkgfile -u
  become: yes
  when: install_pkgfile is changed
