---
- name: Install virtualization packages
  package:
    name: qemu ovmf libvirt virt-manager firewalld ebtables dnsmasq bridge-utils openbsd-netcat
    state: present
  become: yes

- name: Enable/Start libvirtd
  systemd:
    name: libvirtd
    enabled: yes
    state: started
  become: yes

- name: Add main user to groups necessary for managing VMs
  user:
    name: "{{ ansible_user_id }}"
    groups: "{{ item }}"
    append: yes
  become: yes
  loop:
    - libvirt
    - kvm
    - dnsmasq

- name: Modify firewalld backend to iptables
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^FirewallBackend='
    line: 'FirewallBackend=iptables'
  become: yes

- name: Expose OVMF to libvirt/qemu
  blockinfile:
    path: /etc/libvirt/qemu.conf
    insertbefore: '^# ?nvram = \['
    block: |
      nvram = [
        "/usr/share/ovmf/x64/OVMF_CODE.fd:/usr/share/ovmf/x64/OVMF_VARS.fd"
      ]
  become: yes
