# cask before all
brew "caskroom/cask/brew-cask"

# get xquartz, it is a dependency
cask "xquartz"

# brew away
brew "dos2unix"
brew "editorconfig"
brew "fasd"
brew "ffmpeg"
brew "gcc"
brew "gdal"
brew "git"
brew "go"
brew "hub"
brew "jmeter"
brew "jq"
brew "mackup"
brew "mdbtools"
brew "nvm"
brew "pv"
brew "pxz"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-which-ext"
brew "readline"
brew "sqlite"
brew "terminal-notifier"
brew "the_platinum_searcher"
brew "tmux"
brew "unrar"
brew "wget"
brew "wine"
brew "youtube-dl"
brew "zopfli"
brew "zsh"
brew "zsh-lovers"

# emacs-mac
tap "railwaycat/emacsmacport"
brew "emacs-mac"

# casks
cask "adobe-photoshop-lightroom"
cask "caffeine"
cask "firefox"
cask "flux"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "julia"
cask "microsoft-office"
cask "r"
cask "rstudio"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "spectacle"
cask "transmission"
cask "virtualbox"
cask "vlc"
cask "xmind"

# fonts
tap "caskroom/fonts"
cask "font-lato"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
