---
- name: Install xorg
  package:
    name: xorg
    state: present
  become: yes

- name: Install Intel graphics driver
  package:
    name: xf86-video-intel
    state: present
  become: yes

- name: Install mesa
  package:
    name: mesa
    state: present
  become: yes

- name: Install bspwm
  package:
    name: bspwm
    state: present
  become: yes

- name: Install sxhkd
  package:
    name: sxhkd
    state: present
  become: yes

- name: Install rofi
  package:
    name: rofi
    state: present
  become: yes

- name: Install urxvt
  package:
    name: rxvt-unicode
    state: present
  become: yes

- name: create bspwm config dirs
  file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
  with_items:
    - bspwm
    - sxhkd

- name: copy bspwm configuration
  copy:
    src: "{{ item }}rc"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}/{{ item }}rc"
    mode: 0755
  with_items:
    - bspwm
    - sxhkd

# TODO:
# - name: Install polybar
# command: yay -Sy polybar --nouseask

- name: Install lightdm
  package:
    name: lightdm
    state: present
  become: yes

- name: Install lightdm-gtk-greeter
  package:
    name: lightdm-gtk-greeter
    state: present
  become: yes

- name: Enable and start lightdm
  service:
    name: lightdm
    state: started
    enabled: yes
  become: yes
