---
- name: Install xorg
  package:
    name: xorg
    state: present
  become: yes

- name: Install Intel graphics driver
  package:
    name: xf86-video-intel
    state: present
  become: yes

- name: Install mesa
  package:
    name: mesa
    state: present
  become: yes

- name: Install Intel video acceleration driver
  package:
    name: libva-intel-driver
    state: present
  become: yes

- name: Install compton
  package:
    name: compton
    state: present
  become: yes

- name: Install xsel
  package:
    name: xsel
    state: present
  become: yes

- name: Modify Compose locale files with Ccedilla
  lineinfile:
    path: /usr/share/X11/locale/en_US.UTF-8/Compose
    regexp: '^<dead_acute> <C>'
    line: '<dead_acute> <C>                 	: "ร"   Ccedilla # LATIN CAPITAL LETTER C WITH CEDILLA'
  become: yes

- name: Modify Compose locale files with ccedilla
  lineinfile:
    path: /usr/share/X11/locale/en_US.UTF-8/Compose
    regexp: '^<dead_acute> <c>'
    line: '<dead_acute> <c>                 	: "รง"   ccedilla # LATIN SMALL LETTER C WITH CEDILLA'
  become: yes

- name: Set proper keymap for X11
  command: /usr/bin/localectl --no-convert --no-ask-password set-x11-keymap us,us pc105 ,intl grp:shifts_toggle,ctrl:swapcaps,caps:hyper
  args:
    creates: /etc/X11/xorg.conf.d/00-keyboard.conf
  become: yes

- name: Set proper touchpad configuration
  copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
  become: yes

- name: Install bspwm
  package:
    name: bspwm
    state: present
  become: yes

- name: Install sxhkd
  package:
    name: sxhkd
    state: present
  become: yes

- name: Install rofi
  package:
    name: rofi
    state: present
  become: yes

- name: create rofi config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/rofi"
    state: directory

- name: Install urxvt
  package:
    name: rxvt-unicode
    state: present
  become: yes

- name: create bspwm config dirs
  file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
  loop:
    - bspwm
    - sxhkd

- name: copy bspwm configuration
  copy:
    src: "{{ item }}rc"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}/{{ item }}rc"
    mode: 0755
  loop:
    - bspwm
    - sxhkd

- name: Install polybar
  command: yay -S --noconfirm polybar
  args:
    creates: /usr/bin/polybar

- name: copy polybar configuration
  copy:
    src: polybar
    dest: "{{ ansible_env.HOME }}/.config/polybar/config"

- name: Install lightdm
  package:
    name: lightdm
    state: present
  become: yes

- name: Install lightdm-gtk-greeter
  package:
    name: lightdm-gtk-greeter
    state: present
  become: yes

- name: Enable and start lightdm
  service:
    name: lightdm
    state: started
    enabled: yes
  become: yes

- name: copy .Xresources
  copy:
    src: "Xresources"
    dest: "{{ ansible_env.HOME }}/.Xresources"

- name: create .Xresources.d
  file:
    path: "{{ ansible_env.HOME }}/.Xresources.d"
    state: directory

- name: copy .Xresources.d/urxvt
  copy:
    src: "Xresources.d/urxvt"
    dest: "{{ ansible_env.HOME }}/.Xresources.d/urxvt"

- name: Install feh
  package:
    name: feh
    state: present
  become: yes

- name: Install dunst
  package:
    name: dunst
    state: present
  become: yes

- name: create dunst config dirs
  file:
    path: "{{ ansible_env.HOME }}/.config/dunst"
    state: directory

- name: copy dunst configuration
  copy:
    src: "dunstrc"
    dest: "{{ ansible_env.HOME }}/.config/dunst/dunstrc"

- name: Install libnotify
  package:
    name: libnotify
    state: present
  become: yes

- name: Install mpv
  package:
    name: mpv
    state: present
  become: yes

- name: Install xdotool
  package:
    name: xdotool
    state: present
  become: yes

- name: Install maim
  package:
    name: maim
    state: present
  become: yes

- name: create Pictures dir
  file:
    path: "{{ ansible_env.HOME }}/Pictures"
    state: directory

- name: Install clipmenu/notify
  package:
    name: clipnotify clipmenu
    state: present
  become: yes

- name: Enable/Start clipmenud
  systemd:
    name: clipmenud
    enabled: yes
    scope: user
    state: started

- name: Install archlinux-wallpaper
  package:
    name: archlinux-wallpaper
    state: present
  become: yes

- name: Install deepin wallpapers
  package:
    name: deepin-community-wallpapers deepin-wallpapers deepin-wallpapers-plasma
    state: present
  become: yes

- name: Set lightdm wallpaper
  lineinfile:
    path: /etc/lightdm/lightdm-gtk-greeter.conf
    regexp: '^#?background='
    line: 'background=/usr/share/archlinux/wallpaper/archlinux-ekisho-carbonite.jpg'
  become: yes

- name: Set lightdm position
  lineinfile:
    path: /etc/lightdm/lightdm-gtk-greeter.conf
    regexp: '^#?position='
    line: 'position=30%,center 50%,center'
  become: yes

- name: Copy xsession
  copy:
    src: xsession
    dest: "{{ ansible_env.HOME }}/.xsession"
    mode: 0755
