---
- name: Install thinkfan
  command: yay -S --noconfirm thinkfan-git
  args:
    creates: /usr/bin/thinkfan
  become: yes

- name: copy thinkfan configuration
  copy:
    src: thinkfan.conf
    dest: /etc/thinkfan.conf
  become: yes

- name: Install power-related tools
  package:
    name: cpupower powertop
    state: present
  become: yes

- name: Add udev rules to use performance governor on AC power
  copy:
    src: 80-power-governor.rules
    dest: /etc/udev/rules.d/80-power-governor.rules
  become: yes
