---
- name: Install thinkfan
  command: yay -S --noconfirm thinkfan-git
  args:
    creates: /usr/bin/thinkfan
  when: hw_thinkpad

- name: copy thinkfan configuration
  copy:
    src: thinkfan.conf
    dest: /etc/thinkfan.conf
  become: yes
  when: hw_thinkpad

- name: Install power-related tools
  package:
    name: cpupower ethtool powertop smartmontools
    state: present
  become: yes

- name: Install TLP
  package:
    name: tlp tlp-rdw
    state: present
  become: yes
  when: hw_thinkpad
  notify:
    - Mask systemd-rfkill (service)
    - Mask systemd-rfkill (socket)
    - Enable TLP (tlp)
    - Enable TLP (tlp-sleep)
    - Enable TLP (NetworkManager-dispatcher)
