---
- name: Load kernel drivers at boot
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: 'MODULES=(i915)'
  become: yes
  register: modules_list

- name: Disable gzip compression for the initramfs image
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^#?COMPRESSION="gzip"'
    line: '#COMPRESSION="gzip"'
  become: yes

- name: Install lz4
  package:
    name: lz4
    state: present
  become: yes

- name: Enable lz4 compression for the initramfs image
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^#?COMPRESSION="lz4"'
    line: 'COMPRESSION="lz4"'
  become: yes
  register: modules_lz4

- name: Set lz4 compression level to max
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^#?COMPRESSION_OPTIONS'
    line: 'COMPRESSION_OPTIONS=(-12)'
  become: yes
  register: modules_lz4_options

- name: Remake init ram cpio image
  command: mkinitcpio -p linux
  become: yes
  when: modules_list is changed or modules_lz4 is changed or modules_lz4_options is changed
