---
- name: find fishs path
  command: which fish
  register: which_fish

- name: install asdf-nodejs
  shell: "asdf plugin add nodejs"
  args:
    creates: "{{ home }}/.asdf/plugins/nodejs"
    executable: "{{ which_fish.stdout }}"
  register: asdf_nodejs_install

- name: ensure npm global packages
  lineinfile:
    path: "{{ home }}/.default-npm-packages"
    line: "{{ item }}"
    create: yes
  loop: "{{ nodejs_packages }}"

- name: import node.js release team keys
  command: "{{ home }}/.asdf/plugins/nodejs/bin/import-release-team-keyring"
  when: asdf_nodejs_install.changed

- name: install node.js
  shell: "asdf install nodejs {{ nodejs_version }}"
  args:
    creates: "{{ home }}/.asdf/installs/nodejs/{{ nodejs_version }}"
    executable: "{{ which_fish.stdout }}"

- name: set global node.js version
  shell: "asdf global nodejs {{ nodejs_version }}"
  args:
    creates: "{{ home }}/.tool-versions"
    executable: "{{ which_fish.stdout }}"
