---
- name: find fishs path
  command: which fish
  register: which_fish

- name: install nvm
  shell: "fisher install jorgebucaran/nvm.fish"
  args:
    creates: "{{ home }}/.config/fish/functions/nvm.fish"
    executable: "{{ which_fish.stdout }}"

- name: install node.js LTS
  shell: "nvm use lts"
  args:
    creates: "{{ home }}/.config/nvm/version"
    executable: "{{ which_fish.stdout }}"

- name: grab node.js version
  shell: "node --version | tail -c+2"
  args:
    executable: "{{ which_fish.stdout }}"
  register: nodejs_version

- debug:
    msg: "Node.js version is {{ nodejs_version.stdout }}"

- name: install npm global packages
  shell: "npm i -g {{ item }}"
  args:
    creates: "{{ home }}/.config/nvm/{{ nodejs_version.stdout }}/lib/node_modules/{{ item }}"
    executable: "{{ which_fish.stdout }}"
  loop: "{{ nodejs_packages }}"
