---
- name: install latest python2
  homebrew: name=python state=latest

- name: install pip packages to python2
  pip:
    name: "{{ python_packages }}"
    state: latest

- name: install python3
  homebrew: name=python3 state=latest

- name: install pip packages to python3
  pip:
    name: "{{ python_packages }}"
    state: latest
    executable: pip3
