---
- name: Create main user
  user:
    name: "{{ mainuser['name'] }}"
    comment: "{{ mainuser['comment'] }}"
    groups: wheel
    append: yes
    password: "{{ 'mudar123' | password_hash('sha512') }}"
    update_password: on_create
  register: newmainuser

- name: Force new main user to change password
  shell: chage -d 0 "{{ mainuser['name'] }}"
  when: newmainuser.changed

- name: Enable sudo for wheel
  lineinfile:
    path: /etc/sudoers
    regexp: '^(#\s*)?%wheel ALL=\(ALL\) ALL'
    line: '%wheel ALL=(ALL) ALL'
    validate: '/usr/bin/visudo -cf %s'

- name: Lock root password
  user:
    name: root
    password_lock: yes
