---
- name: install tmux
  package:
    name: tmux
    state: present
  become: yes

- name: install tmuxp
  package:
    name: tmuxp
    state: present
  become: yes

- name: link tmux.conf
  file: path="{{ home }}/.tmux.conf" src="{{ src_dir }}/dotfiles/tmux/tmux.conf" state=link force=yes

- name: install tmux plugin manager (tpm)
  git: repo=https://github.com/tmux-plugins/tpm.git dest="{{ home }}/.tmux/plugins/tpm"
