---
- name: Install docker
  package:
    name: docker.io
    state: present
  become: yes

- name: Add main user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes

- name: Enable and start docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Install docker-compose
  package:
    name: docker-compose
    state: present
  become: yes
