---
- name: add neovim tap
  homebrew_tap: tap=neovim/neovim state=present
  when: ansible_os_family == 'Darwin'

- name: install neovim
  package:
    name: neovim
    state: present
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"

- name: install python-neovim
  package:
    name: python-neovim
    state: present
  become: yes
  when: ansible_os_family == 'Archlinux'

- name: create neovim config dir
  file: path="{{ home }}/.config/nvim" state=directory

- name: link init.vim (neovim)
  file: path="{{ home }}/.config/nvim/init.vim" src="{{ src_dir }}/dotfiles/nvim/init.vim" state=link force=yes
